### ISSUE TITLE
Version picker render error

### ISSUE THREAD

**Issue by freekmurze** [spatie/docs.spatie.be-old#114]
On https://docs.spatie.be/laravel-medialibrary/v5/introduction

![screen shot 2017-02-02 at 20 12 44](https://cloud.githubusercontent.com/assets/483853/22564225/0a7079a6-e984-11e6-85e1-dbbcad679018.jpg)

**Comment by morloderex** [comment]
I have created a which fixes this bug!

**Comment by freekmurze** [comment]
Problem persists...

**Comment by morloderex** [comment]
Oh sorry i was not really aware of how the sass were compiled. :)
