### ISSUE TITLE
Deadlink in medialibrary package docs

### ISSUE THREAD

**Issue by breadlesscode** [spatie/docs.spatie.be-old#138]
hi spatie-team,

thaaaaaaaaank you for all of your great work (postcard is in progress).

https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/overriding-default-filesystem-behaviour

The link above is a dead link but it is linked in the right navigation.

greetings Marv =)

**Comment by freekmurze** [comment]
Fixed, thanks.

The correct link is https://docs.spatie.be/laravel-medialibrary/v5/advanced-usage/overriding-the-default-filesystem-behaviour
