### ISSUE TITLE
404 on Overriding default filesystem behaviour

### ISSUE THREAD

**Issue by matrunchyk** [spatie/docs.spatie.be-old#166]
Hello guys, please take a look when you have a time
![Alt text](https://monosnap.com/file/HCykN6uSspHGLfR5XJ7GBiy2EnQZDA.png)

I'm also wondering, is there any possibility to resize/crop a particular file on the fly before/after adding to a media collection?

Something like
```
$media = $model->addMedia($request->file('form_files.0'))
    ->crop($request->left, $request->top, $request->width, $request->height)
    ->toMediaCollection('avatars', 'avatar')
;
```

(Sorry I should have to ask it separately probably)

**Comment by freekmurze** [comment]
Hi,

link has been fixed.

You can easily manipulate the image before adding it to the medialibrary using [our image package](https://docs.spatie.be/image/v1/introduction)
