### ISSUE TITLE
Watermarks 404

### ISSUE THREAD

**Issue by timgavin** [spatie/docs.spatie.be-old#175]
Go here: https://docs.spatie.be/image/v1/image-manipulations/overview

Scroll down to **Watermarks** and click any link; results in 'Docs not found'

https://docs.spatie.be/image/v1/image-manipulations/watermark

**Comment by timgavin** [comment]
Actually, now that I'm clicking links on this page - https://docs.spatie.be/image/v1/image-manipulations/overview - none of the anchors are working either.

**Comment by freekmurze** [comment]
Thanks for notifying me. I'll take a look at this soon. If you have the time, I'd appreciate a PR that fixes this.
