### ISSUE TITLE
[v7] Downloading multiple files incorrect code sample?

### ISSUE THREAD

**Issue by Omranic** [spatie/docs.spatie.be-old#236]
I'm not sure if the code sample for multiple file downloads is correct or not, would you give it a look please: https://github.com/spatie/docs.spatie.be/blob/master/resources/views/laravel-medialibrary/v7/downloading-media/downloading-multiple-files.md

`$mediaItem` / `$media` / `$yourModel` / `$allMedia`

Thanks for the great package 👍

**Comment by freekmurze** [comment]
Fixed it, thanks for bringing this to my attention.
