### ISSUE TITLE
Notes about MediaHasBeenAdded event

### ISSUE THREAD

**Issue by unikapps** [spatie/docs.spatie.be-old#244]
I needed to add custom propeties after the media has been saved, and i find that the method `$media->getMedia()` from the example does not exists instead i used `$media->media.`

Alsoe to persiste the properties to DB after calling `$media->setCustomPropery() ` i needed to do `$media->save()`

I think it's nice to point to this in the doc.

**Comment by freekmurze** [comment]
Feel free to send PRs to improve the docs.
