### ISSUE TITLE
No Spatie\MediaLibrary\HasMedia\Interfaces

### ISSUE THREAD

**Issue by reza-akbari** [spatie/docs.spatie.be-old#275]
Hi, thank you for creating nice documentation

upgraded from version 6.0.0

There is no Spatie\MediaLibrary\HasMedia\Interfaces
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

**Comment by freekmurze** [comment]
Feel free to send PRs to the docs. There's an `edit` button on top of every page.
