### ISSUE TITLE
Link class not found in example code

### ISSUE THREAD

**Issue by jrebs** [spatie/docs.spatie.be-old#282]
On the menu example page on the introduction document, there is a sample showing ```->add(Link::to(x, y))``` syntax as an alternative to ```->link(x, y)```. When I try to use the former in a blade PHP template (within {{ }}), I get an error that the Link class is not found (I am using a "laravel new app" application and did require spatie/menu and spatie/laravel-menu. If I explicitly call it with ```->add(Spatie\Menu\Link::to(x, y))```, then it works.

Am I doing something wrong that this namespace isn't present automatically? Is this expected? Or outdated doc?

**Comment by TVke** [comment]
Hi @jrebs 

I would recommend reading this page: https://docs.spatie.be/menu/v2/installation-and-setup
If you have questions about a package, I suggest you open an issue in the package repository (in this case: https://github.com/spatie/laravel-menu).

The issues here would contain wrong information or a general site issue.

Hope this helps.

**Comment by jrebs** [comment]
Thanks @TVke I will close this off.
