### ISSUE TITLE
IP blocked in Russia

### ISSUE THREAD

**Issue by ghost** [spatie/docs.spatie.be-old#387]
IP 46.101.151.54 (docs.spatie.be) blocked in Russia.
Therefore, the documentation in Russia is not available. 

I am sure this is an accident. Just decided to let you know that there is such a problem.

You can check here: https://isitblockedinrussia.com/?host=https://docs.spatie.be

**Comment by freekmurze** [comment]
That's a shame. You can also read the docs inside this repo directly: https://github.com/spatie/docs.spatie.be/tree/master/resources/views
