### ISSUE TITLE
installation on fresh laravel fails

### ISSUE THREAD

**Issue by zabetta** [spatie/docs.spatie.be-old#401]
"PHP " : "7.2.8",
"laravel/framework": "5.8.*",

> composer require spatie/laravel-server-monitor:^1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/console v4.2.5
    - Conclusion: don't install symfony/console v4.2.5
    - symfony/process 3.2.x-dev conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.0 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.0-BETA1 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.0-RC1 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.0-RC2 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.1 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.10 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.11 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.12 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.13 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.14 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.2 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.3 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.4 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.5 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.6 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.7 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.8 conflicts with symfony/console[v4.2.5].
    - symfony/process v3.2.9 conflicts with symfony/console[v4.2.5].
    - Installation request for symfony/console (locked at v4.2.5) -> satisfiable by symfony/console[v4.2.5].
    - Installation request for spatie/laravel-server-monitor 1.0 -> satisfiable by spatie/laravel-server-monitor[1.0.0].
    - Conclusion: don't install symfony/process v4.2.5|install symfony/process 3.2.x-dev|install symfony/process v3.2.0|install symfony/process v3.2.0-BETA1|install symfony/process v3.2.0-RC1|install symfony/process v3.2.0-RC2|install symfony/process v3.2.1|install symfony/process v3.2.10|install symfony/process v3.2.11|install symfony/process v3.2.12|install symfony/process v3.2.13|install symfony/process v3.2.14|install symfony/process v3.2.2|install symfony/process v3.2.3|install symfony/process v3.2.4|install symfony/process v3.2.5|install symfony/process v3.2.6|install symfony/process v3.2.7|install symfony/process v3.2.8|install symfony/process v3.2.9
    - Conclusion: remove symfony/process v4.2.5|install symfony/process 3.2.x-dev|install symfony/process v3.2.0|install symfony/process v3.2.0-BETA1|install symfony/process v3.2.0-RC1|install symfony/process v3.2.0-RC2|install symfony/process v3.2.1|install symfony/process v3.2.10|install symfony/process v3.2.11|install symfony/process v3.2.12|install symfony/process v3.2.13|install symfony/process v3.2.14|install symfony/process v3.2.2|install symfony/process v3.2.3|install symfony/process v3.2.4|install symfony/process v3.2.5|install symfony/process v3.2.6|install symfony/process v3.2.7|install symfony/process v3.2.8|install symfony/process v3.2.9
    - spatie/laravel-server-monitor 1.0.0 requires symfony/process ^3.2 -> satisfiable by symfony/process[3.2.x-dev, 3.3.x-dev, 3.4.x-dev, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/process[3.3.x-dev, v4.2.5].
    - Can only install one of: symfony/process[3.4.x-dev, v4.2.5].
    - Can only install one of: symfony/process[v3.3.0, v4.2.5].
    - Can only install one of: symfony/process[v3.3.0-BETA1, v4.2.5].
    - Can only install one of: symfony/process[v3.3.0-RC1, v4.2.5].
    - Can only install one of: symfony/process[v3.3.1, v4.2.5].
    - Can only install one of: symfony/process[v3.3.10, v4.2.5].
    - Can only install one of: symfony/process[v3.3.11, v4.2.5].
    - Can only install one of: symfony/process[v3.3.12, v4.2.5].
    - Can only install one of: symfony/process[v3.3.13, v4.2.5].
    - Can only install one of: symfony/process[v3.3.14, v4.2.5].
    - Can only install one of: symfony/process[v3.3.15, v4.2.5].
    - Can only install one of: symfony/process[v3.3.16, v4.2.5].
    - Can only install one of: symfony/process[v3.3.17, v4.2.5].
    - Can only install one of: symfony/process[v3.3.18, v4.2.5].
    - Can only install one of: symfony/process[v3.3.2, v4.2.5].
    - Can only install one of: symfony/process[v3.3.3, v4.2.5].
    - Can only install one of: symfony/process[v3.3.4, v4.2.5].
    - Can only install one of: symfony/process[v3.3.5, v4.2.5].
    - Can only install one of: symfony/process[v3.3.6, v4.2.5].
    - Can only install one of: symfony/process[v3.3.7, v4.2.5].
    - Can only install one of: symfony/process[v3.3.8, v4.2.5].
    - Can only install one of: symfony/process[v3.3.9, v4.2.5].
    - Can only install one of: symfony/process[v3.4.0, v4.2.5].
    - Can only install one of: symfony/process[v3.4.0-BETA1, v4.2.5].
    - Can only install one of: symfony/process[v3.4.0-BETA2, v4.2.5].
    - Can only install one of: symfony/process[v3.4.0-BETA3, v4.2.5].
    - Can only install one of: symfony/process[v3.4.0-BETA4, v4.2.5].
    - Can only install one of: symfony/process[v3.4.0-RC1, v4.2.5].
    - Can only install one of: symfony/process[v3.4.0-RC2, v4.2.5].
    - Can only install one of: symfony/process[v3.4.1, v4.2.5].
    - Can only install one of: symfony/process[v3.4.10, v4.2.5].
    - Can only install one of: symfony/process[v3.4.11, v4.2.5].
    - Can only install one of: symfony/process[v3.4.12, v4.2.5].
    - Can only install one of: symfony/process[v3.4.13, v4.2.5].
    - Can only install one of: symfony/process[v3.4.14, v4.2.5].
    - Can only install one of: symfony/process[v3.4.15, v4.2.5].
    - Can only install one of: symfony/process[v3.4.16, v4.2.5].
    - Can only install one of: symfony/process[v3.4.17, v4.2.5].
    - Can only install one of: symfony/process[v3.4.18, v4.2.5].
    - Can only install one of: symfony/process[v3.4.19, v4.2.5].
    - Can only install one of: symfony/process[v3.4.2, v4.2.5].
    - Can only install one of: symfony/process[v3.4.20, v4.2.5].
    - Can only install one of: symfony/process[v3.4.21, v4.2.5].
    - Can only install one of: symfony/process[v3.4.22, v4.2.5].
    - Can only install one of: symfony/process[v3.4.23, v4.2.5].
    - Can only install one of: symfony/process[v3.4.24, v4.2.5].
    - Can only install one of: symfony/process[v3.4.3, v4.2.5].
    - Can only install one of: symfony/process[v3.4.4, v4.2.5].
    - Can only install one of: symfony/process[v3.4.5, v4.2.5].
    - Can only install one of: symfony/process[v3.4.6, v4.2.5].
    - Can only install one of: symfony/process[v3.4.7, v4.2.5].
    - Can only install one of: symfony/process[v3.4.8, v4.2.5].
    - Can only install one of: symfony/process[v3.4.9, v4.2.5].
    - Installation request for symfony/process (locked at v4.2.5) -> satisfiable by symfony/process[v4.2.5].

Installation failed, reverting ./composer.json to its original content.

solved removing version ^1.0 from composer require string

**Comment by freekmurze** [comment]
I'm not sure if this issue belongs to docs.spatie.be
