### ISSUE TITLE
Add a note explaining the differences between Model implementations

### ISSUE THREAD

**Issue by anchepiece** [spatie/docs.spatie.be-old#66]
Browsing the documentation I noticed that you have two different interfaces available to apply, but there is no place pointing out the difference. 

Without conversions

```
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class NewsItem extends Model implements HasMedia
{
    use HasMediaTrait;
```

Using conversions

```
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;

class NewsItem extends Model implements HasMediaConversions
{
    use HasMediaTrait;

    public function registerMediaConversions()
    {
        $this->addMediaConversion('thumb')
             ->setManipulations(['w' => 368, 'h' => 232])
             ->performOnCollections('images');
    }

```

Maybe even in the preparing-your-model section, just point out that if you plan on using conversions, that you should read the alternate page at converting-images/defining-conversions.

**Comment by freekmurze** [comment]
Thanks for your proposal. [I've made that change](https://docs.spatie.be/laravel-medialibrary/v4/basic-usage/preparing-your-model).

If you want to change something else to our docs, notice that there is an `edit` button at the top of every page.

**Comment by anchepiece** [comment]
Perfect! I will use the edit tool in the future.
